version: "3.7"
services:
  lic-microservice-base-provider:
    #image: registry.cn-shenzhen.aliyuncs.com/lic-doc/lic-microservice-base-provider:main
    container_name: lic-microservice-base-provider
    build:
      #context: ../
      dockerfile: lic-microservice-base-provider/Dockerfile
    ports:
      - "9008:9008"
    privileged: true
    environment:
      SPRING_PROFILES_ACTIVE: prod
    network_mode: host